# -----------------------------
# PersistentVolumeClaim (Single PVC)
# -----------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-storage-pvc
  namespace: mlflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: ceph-ssd
  volumeMode: Filesystem

---
# -----------------------------
# MLflow Deployment
# -----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: cdjs/mlflow-oidc:dev
          imagePullPolicy: Always
          args:
            - "mlflow"
            - "server"
            - "--app-name"
            - "oidc-auth"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "5000"
            - "--artifacts-destination"
            - "s3://drai-mlflow-test"
            - "--serve-artifacts"
            - "--disable-security-middleware"
          ports:
            - containerPort: 5000
          env:
            - name: OIDC_DISCOVERY_URL
              value: https://keycloak.test.drai.auckland.ac.nz/realms/drai/.well-known/openid-configuration
            - name: OIDC_CLIENT_ID
              value: mlflow-test
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mlflow-secret
                  key: MLFLOW_OIDC_CLIENT_SECRET
            - name: OIDC_PROVIDER_DISPLAY_NAME
              value: Login with DRAI Keycloak
            - name: OIDC_REDIRECT_URI
              value: https://mlflow.test.drai.auckland.ac.nz/callback
            - name: OIDC_SCOPE
              value: openid email profile
            - name: LOG_LEVEL
              value: INFO
            - name: DEFAULT_MLFLOW_PERMISSION
              value: NO_PERMISSIONS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgres-secret
                  key: password
            - name: MLFLOW_BACKEND_STORE_URI
              value: "postgresql+psycopg2://mlflow:$(DB_PASSWORD)@mlflow-postgres-postgresql.mlflow.svc.cluster.local:5432/mlflow"
            - name: OIDC_USERS_DB_URI
              value: "postgresql+psycopg2://mlflow:$(DB_PASSWORD)@mlflow-postgres-postgresql.mlflow.svc.cluster.local:5432/mlflow_auth"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-secret
                  key: MLFLOW_AWS_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-secret
                  key: MLFLOW_AWS_SECRET_KEY
            - name: MLFLOW_S3_ENDPOINT_URL
              value: https://object.akl-1.cloud.nesi.org.nz
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_S3_ADDRESSING_STYLE
              value: path
            - name: AWS_REQUEST_CHECKSUM_CALCULATION
              value: when_required
            - name: AWS_RESPONSE_CHECKSUM_CALCULATION
              value: when_required
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"

---
# -----------------------------
# ClusterIP Service
# -----------------------------
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
